#!/usr/bin/env node
import { Command } from 'commander';
import fs from 'fs-extra';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { ui } from './lib/ui.mjs';
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const { version, description } = JSON.parse(await fs.readFile(join(__dirname, '..', 'package.json'), 'utf-8'));
const program = new Command();
program.name('claude-antislop').version(version).description(description).showHelpAfterError();
program.command('install').description('Install plugin').option('--init-memory', 'Initialize memory').option('--verbose', 'Verbose').action(async (o) => { try { const { install } = await import('./lib/install.mjs'); await install(o); } catch (e) { ui.error(e.message); process.exit(1); } });
program.command('status').description('Show status').option('--verbose', 'Verbose').action(async (o) => { try { const { showStatus } = await import('./lib/status.mjs'); await showStatus(o); } catch (e) { ui.error(e.message); process.exit(1); } });
program.command('scan').description('Scan repo').option('--repo <path>', 'Repo path').option('--output <path>', 'Output').option('--verbose', 'Verbose').action(async (o) => { try { const { scan } = await import('./lib/scan.mjs'); await scan(o); } catch (e) { ui.error(e.message); process.exit(1); } });
program.command('learn-from-git').description('Learn from Git').option('--repo <path>', 'Repo').option('--recent <period>', 'Period', '30d').option('--verbose', 'Verbose').action(async (o) => { try { const { learn } = await import('./lib/learn.mjs'); await learn(o); } catch (e) { ui.error(e.message); process.exit(1); } });
program.command('memory-search').description('Search memory').option('--query <text>', 'Query').option('--category <name>', 'Category').option('--limit <n>', 'Limit', '5').option('--fuzzy', 'Fuzzy', true).action(async (o) => { try { const { memorySearch } = await import('./lib/memory.mjs'); console.log(JSON.stringify(await memorySearch(o), null, 2)); } catch (e) { ui.error(e.message); process.exit(1); } });
program.command('memory-write').description('Write memory').option('--category <name>', 'Category').option('--filename <name>', 'Filename').option('--content <text>', 'Content').option('--append', 'Append').action(async (o) => { try { const { memoryWrite } = await import('./lib/memory.mjs'); console.log(JSON.stringify(await memoryWrite(o), null, 2)); } catch (e) { ui.error(e.message); process.exit(1); } });
program.command('code-quality-check').description('Quality checks').option('--code <code>', 'Code').option('--language <lang>', 'Language').option('--checks <types>', 'Checks').action(async (o) => { try { const { codeQualityCheck } = await import('./lib/quality.mjs'); console.log(JSON.stringify(await codeQualityCheck({ code: o.code, language: o.language, checks: o.checks.split(',') }), null, 2)); } catch (e) { ui.error(e.message); process.exit(1); } });
program.command('mcp-server').description('Start MCP').action(async () => { try { const { startServer } = await import('../mcp/mcp-server-index.mjs'); await startServer(); } catch (e) { ui.error(e.message); process.exit(1); } });
program.command('init-memory').description('Init memory').option('--force', 'Force').option('--verbose', 'Verbose').action(async (o) => { try { const { initMemory } = await import('./lib/memory.mjs'); await initMemory(o); } catch (e) { ui.error(e.message); process.exit(1); } });
program.command('completion').description('Shell completions').argument('<shell>', 'bash|zsh|fish|install').option('--path <dir>', 'Target dir').action(async (shell, o) => { try { const { getCompletionScript, installCompletion, getSupportedShells } = await import('./lib/completion.mjs'); const shells = getSupportedShells(); if (shell === 'install') { const target = o.path ? null : process.env.SHELL?.split('/').pop() || 'bash'; const r = await installCompletion(target || 'bash', o.path); ui.success(`Installed for ${r.shell}`); ui.info(`Destination: ${r.destination}`); console.log(); ui.info(r.restartHint); } else if (shells.includes(shell)) { console.log(await getCompletionScript(shell)); } else { ui.error(`Unsupported: ${shell}. Supported: ${shells.join(', ')}`); process.exit(1); } } catch (e) { ui.error(e.message); process.exit(1); } });
program.command('wizard').description('Run first-run setup wizard').action(async () => { try { const { firstRunWizard } = await import('./lib/wizard.mjs'); await firstRunWizard(); } catch (e) { ui.error(e.message); process.exit(1); } });
program.parse(process.argv);
if (!process.argv.slice(2).length) program.outputHelp();
