#!/usr/bin/env node
import { Command } from 'commander';
import fs from 'fs-extra';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { ui } from './lib/ui.mjs';
import { printOutput, createSuccessResponse, createErrorResponse } from './lib/output.mjs';
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const { version, description } = JSON.parse(await fs.readFile(join(__dirname, '..', 'package.json'), 'utf-8'));
const program = new Command();
program.name('claude-antislop').version(version).description(description).showHelpAfterError();

const globalFlags = [
  { flags: '--json', desc: 'Output JSON (machine-readable)' },
  { flags: '--quiet, -q', desc: 'Suppress output (exit code only)' }
];

program.command('install').description('Install plugin').option('--init-memory', 'Initialize memory').option('--verbose', 'Verbose').option('--json', 'JSON output').option('--quiet, -q', 'Quiet').action(async (o) => { try { const { install } = await import('./lib/install.mjs'); await install(o); const res = createSuccessResponse('Installation complete'); printOutput(res, o); } catch (e) { const res = createErrorResponse(e.message); printOutput(res, o); process.exit(1); } });
program.command('status').description('Show status').option('--verbose', 'Verbose').option('--json', 'JSON output').option('--quiet, -q', 'Quiet').action(async (o) => { try { const { showStatus } = await import('./lib/status.mjs'); await showStatus(o); const res = createSuccessResponse('Status check complete'); printOutput(res, o); } catch (e) { const res = createErrorResponse(e.message); printOutput(res, o); process.exit(1); } });
program.command('scan').description('Scan repo').option('--repo <path>', 'Repo path').option('--output <path>', 'Output').option('--verbose', 'Verbose').option('--json', 'JSON output').option('--quiet, -q', 'Quiet').action(async (o) => { try { const { scan } = await import('./lib/scan.mjs'); await scan(o); const res = createSuccessResponse('Scan complete'); printOutput(res, o); } catch (e) { const res = createErrorResponse(e.message); printOutput(res, o); process.exit(1); } });
program.command('learn-from-git').description('Learn from Git').option('--repo <path>', 'Repo').option('--recent <period>', 'Period', '30d').option('--verbose', 'Verbose').option('--json', 'JSON output').option('--quiet, -q', 'Quiet').action(async (o) => { try { const { learn } = await import('./lib/learn.mjs'); await learn(o); const res = createSuccessResponse('Learning complete'); printOutput(res, o); } catch (e) { const res = createErrorResponse(e.message); printOutput(res, o); process.exit(1); } });
program.command('memory-search').description('Search memory').option('--query <text>', 'Query').option('--category <name>', 'Category').option('--limit <n>', 'Limit', '5').option('--fuzzy', 'Fuzzy', true).option('--json', 'JSON output').option('--quiet, -q', 'Quiet').action(async (o) => { try { const { memorySearch } = await import('./lib/memory.mjs'); const result = await memorySearch(o); const res = createSuccessResponse(`Found ${result.count || 0} results`, result); printOutput(res, o); } catch (e) { const res = createErrorResponse(e.message); printOutput(res, o); process.exit(1); } });
program.command('memory-write').description('Write memory').option('--category <name>', 'Category').option('--filename <name>', 'Filename').option('--content <text>', 'Content').option('--append', 'Append').option('--json', 'JSON output').option('--quiet, -q', 'Quiet').action(async (o) => { try { const { memoryWrite } = await import('./lib/memory.mjs'); const result = await memoryWrite(o); const res = createSuccessResponse('Memory written', result); printOutput(res, o); } catch (e) { const res = createErrorResponse(e.message); printOutput(res, o); process.exit(1); } });
program.command('code-quality-check').description('Quality checks').option('--code <code>', 'Code').option('--language <lang>', 'Language').option('--checks <types>', 'Checks').option('--json', 'JSON output').option('--quiet, -q', 'Quiet').action(async (o) => { try { const { codeQualityCheck } = await import('./lib/quality.mjs'); const checks = o.checks ? o.checks.split(',') : ['lint','typecheck','prettier']; const result = await codeQualityCheck({ code: o.code, language: o.language, checks }); const res = createSuccessResponse('Quality check complete', result); printOutput(res, o); } catch (e) { const res = createErrorResponse(e.message); printOutput(res, o); process.exit(1); } });
program.command('mcp-server').description('Start MCP').option('--json', 'JSON output').option('--quiet, -q', 'Quiet').action(async (o) => { try { const { startServer } = await import('../mcp/mcp-server-index.mjs'); await startServer(); const res = createSuccessResponse('MCP server started'); printOutput(res, o); } catch (e) { const res = createErrorResponse(e.message); printOutput(res, o); process.exit(1); } });
program.command('init-memory').description('Init memory').option('--force', 'Force').option('--verbose', 'Verbose').option('--json', 'JSON output').option('--quiet, -q', 'Quiet').action(async (o) => { try { const { initMemory } = await import('./lib/memory.mjs'); await initMemory(o); const res = createSuccessResponse('Memory initialized'); printOutput(res, o); } catch (e) { const res = createErrorResponse(e.message); printOutput(res, o); process.exit(1); } });
program.command('completion').description('Shell completions').argument('<shell>', 'bash|zsh|fish|install').option('--path <dir>', 'Target dir').option('--json', 'JSON output').option('--quiet, -q', 'Quiet').action(async (shell, o) => { try { const { getCompletionScript, installCompletion, getSupportedShells } = await import('./lib/completion.mjs'); const shells = getSupportedShells(); if (shell === 'install') { const target = o.path ? null : process.env.SHELL?.split('/').pop() || 'bash'; const r = await installCompletion(target || 'bash', o.path); const res = createSuccessResponse(`Completion installed for ${r.shell}`, { shell, destination: r.destination }, r.restartHint); printOutput(res, o); } else if (shells.includes(shell)) { const script = await getCompletionScript(shell); if (o.json) { console.log(JSON.stringify({ success: true, message: 'Completion script', data: { script }, timestamp: new Date().toISOString() }, null, 2)); } else { console.log(script); } } else { const res = createErrorResponse(`Unsupported shell: ${shell}`, { supported: shells }); printOutput(res, o); process.exit(1); } } catch (e) { const res = createErrorResponse(e.message); printOutput(res, o); process.exit(1); } });
program.command('wizard').description('Run setup wizard').option('--json', 'JSON output').option('--quiet, -q', 'Quiet').action(async (o) => { try { const { firstRunWizard } = await import('./lib/wizard.mjs'); const config = await firstRunWizard(); const res = createSuccessResponse('Setup complete', config); printOutput(res, o); } catch (e) { const res = createErrorResponse(e.message); printOutput(res, o); process.exit(1); } });

program.parse(process.argv);
if (!process.argv.slice(2).length) program.outputHelp();
