import fs from 'fs-extra';
import { join } from 'path';

const SUPPORTED_LOCALES = ['en', 'fr', 'es', 'de', 'zh', 'ja'];
const DEFAULT_LOCALE = 'en';
const HOME_DIR = process.env.HOME || process.env.USERPROFILE;
const CONFIG_PATH = join(HOME_DIR, '.claude-antislop', 'config.json');

const translations = {
  en: {'success.install':'Installation complete','success.status':'Status check complete','success.scan':'Scan complete','success.learn':'Learning complete','success.memoryInit':'Memory initialized','success.memoryWrite':'Memory written','success.quality':'Quality check complete','success.completion':'Completion installed for {shell}','success.wizard':'Setup complete','error.install':'Installation failed','error.status':'Status check failed','error.scan':'Scan failed','error.learn':'Learning failed','error.memory':'Memory operation failed','error.quality':'Quality check failed','error.completion':'Completion failed','error.wizard':'Setup wizard failed','error.unsupportedShell':'Unsupported shell: {shell}','error.invalidLocale':'Unsupported locale: {locale}','hint.supportedShells':'Supported shells: {shells}','hint.initMemory':"Run 'claude-antislop init-memory' first",'wizard.title':'🚀 Claude Anti-Slop Setup Wizard','wizard.welcome':"Welcome! Let's set up Claude Anti-Slop for your workflow.",'wizard.stack':'Select your stack','wizard.locale':'Select your locale','wizard.features':'Configure optional features','wizard.memory':'Initialize memory','wizard.completion':'Shell completion','wizard.save':'Save configuration','wizard.complete':'✅ Setup Complete!','common.enabled':'enabled','common.disabled':'disabled'},
  fr: {'success.install':'Installation terminée','success.status':'Vérification du statut terminée','success.scan':'Analyse terminée','success.learn':'Apprentissage terminé','success.memoryInit':'Mémoire initialisée','success.memoryWrite':'Mémoire enregistrée','success.quality':'Vérification de qualité terminée','success.completion':'Complétion installée pour {shell}','success.wizard':'Configuration terminée','error.install':"Échec de l'installation",'error.status':'Échec de la vérification du statut','error.scan':"Échec de l'analyse",'error.learn':"Échec de l'apprentissage",'error.memory':'Échec de l’opération de mémoire','error.quality':'Échec de la vérification de qualité','error.completion':'Échec de la complétion','error.wizard':'Échec de l’assistant de configuration','error.unsupportedShell':'Shell non pris en charge : {shell}','error.invalidLocale':'Langue non prise en charge : {locale}','hint.supportedShells':'Shells pris en charge : {shells}','wizard.title':'🚀 Assistant de configuration Claude Anti-Slop','wizard.welcome':'Bienvenue ! Configurons Claude Anti-Slop pour votre workflow.','wizard.stack':'Sélectionnez votre stack','wizard.locale':'Sélectionnez votre langue','wizard.features':'Configurez les fonctionnalités optionnelles','wizard.memory':'Initialiser la mémoire','wizard.completion':'Complétion shell','wizard.save':'Enregistrer la configuration','wizard.complete':'✅ Configuration terminée !','common.enabled':'activé','common.disabled':'désactivé'},
  es: {'success.install':'Instalación completada','success.status':'Comprobación de estado completada','success.scan':'Análisis completado','success.learn':'Aprendizaje completado','success.memoryInit':'Memoria inicializada','success.memoryWrite':'Memoria guardada','success.quality':'Comprobación de calidad completada','success.completion':'Autocompletado instalado para {shell}','success.wizard':'Configuración completada','error.install':'Error de instalación','error.status':'Error al comprobar el estado','error.scan':'Error de análisis','error.learn':'Error de aprendizaje','error.memory':'Error de operación de memoria','error.quality':'Error de comprobación de calidad','error.completion':'Error de autocompletado','error.wizard':'Error del asistente de configuración','error.unsupportedShell':'Shell no compatible: {shell}','error.invalidLocale':'Idioma no compatible: {locale}','hint.supportedShells':'Shells compatibles: {shells}','wizard.title':'🚀 Asistente de configuración de Claude Anti-Slop','wizard.welcome':'¡Bienvenido! Configuremos Claude Anti-Slop para tu flujo de trabajo.','wizard.stack':'Selecciona tu stack','wizard.locale':'Selecciona tu idioma','wizard.features':'Configura funciones opcionales','wizard.memory':'Inicializar memoria','wizard.completion':'Autocompletado de shell','wizard.save':'Guardar configuración','wizard.complete':'✅ ¡Configuración completada!','common.enabled':'activado','common.disabled':'desactivado'},
  de: {'success.install':'Installation abgeschlossen','success.status':'Statusprüfung abgeschlossen','success.scan':'Scan abgeschlossen','success.learn':'Lernen abgeschlossen','success.memoryInit':'Speicher initialisiert','success.memoryWrite':'Speicher gespeichert','success.quality':'Qualitätsprüfung abgeschlossen','success.completion':'Vervollständigung für {shell} installiert','success.wizard':'Einrichtung abgeschlossen','error.install':'Installation fehlgeschlagen','error.status':'Statusprüfung fehlgeschlagen','error.scan':'Scan fehlgeschlagen','error.learn':'Lernen fehlgeschlagen','error.memory':'Speicheroperation fehlgeschlagen','error.quality':'Qualitätsprüfung fehlgeschlagen','error.completion':'Vervollständigung fehlgeschlagen','error.wizard':'Einrichtungsassistent fehlgeschlagen','error.unsupportedShell':'Nicht unterstützte Shell: {shell}','error.invalidLocale':'Nicht unterstützte Sprache: {locale}','hint.supportedShells':'Unterstützte Shells: {shells}','wizard.title':'🚀 Claude Anti-Slop Einrichtungsassistent','wizard.welcome':'Willkommen! Lass uns Claude Anti-Slop einrichten.','wizard.stack':'Wähle deinen Stack','wizard.locale':'Wähle deine Sprache','wizard.features':'Optionale Funktionen konfigurieren','wizard.memory':'Speicher initialisieren','wizard.completion':'Shell-Vervollständigung','wizard.save':'Konfiguration speichern','wizard.complete':'✅ Einrichtung abgeschlossen!','common.enabled':'aktiviert','common.disabled':'deaktiviert'},
  zh: {'success.install':'安装完成','success.status':'状态检查完成','success.scan':'扫描完成','success.learn':'学习完成','success.memoryInit':'记忆已初始化','success.memoryWrite':'记忆已保存','success.quality':'质量检查完成','success.completion':'已为 {shell} 安装补全','success.wizard':'设置完成','error.install':'安装失败','error.status':'状态检查失败','error.scan':'扫描失败','error.learn':'学习失败','error.memory':'记忆操作失败','error.quality':'质量检查失败','error.completion':'补全安装失败','error.wizard':'设置向导失败','error.unsupportedShell':'不支持的 Shell：{shell}','error.invalidLocale':'不支持的语言：{locale}','hint.supportedShells':'支持的 Shell：{shells}','wizard.title':'🚀 Claude Anti-Slop 设置向导','wizard.welcome':'欢迎！让我们为您的工作流程设置 Claude Anti-Slop。','wizard.stack':'选择您的技术栈','wizard.locale':'选择您的语言','wizard.features':'配置可选功能','wizard.memory':'初始化记忆','wizard.completion':'Shell 补全','wizard.save':'保存配置','wizard.complete':'✅ 设置完成！','common.enabled':'已启用','common.disabled':'已禁用'},
  ja: {'success.install':'インストールが完了しました','success.status':'ステータス確認が完了しました','success.scan':'スキャンが完了しました','success.learn':'学習が完了しました','success.memoryInit':'メモリを初期化しました','success.memoryWrite':'メモリを保存しました','success.quality':'品質チェックが完了しました','success.completion':'{shell} の補完をインストールしました','success.wizard':'セットアップが完了しました','error.install':'インストールに失敗しました','error.status':'ステータス確認に失敗しました','error.scan':'スキャンに失敗しました','error.learn':'学習に失敗しました','error.memory':'メモリ操作に失敗しました','error.quality':'品質チェックに失敗しました','error.completion':'補完のインストールに失敗しました','error.wizard':'セットアップウィザードに失敗しました','error.unsupportedShell':'サポートされていないシェル: {shell}','error.invalidLocale':'サポートされていない言語: {locale}','hint.supportedShells':'サポートされているシェル: {shells}','wizard.title':'🚀 Claude Anti-Slop セットアップウィザード','wizard.welcome':'ようこそ！ワークフロー用に Claude Anti-Slop を設定しましょう。','wizard.stack':'スタックを選択','wizard.locale':'言語を選択','wizard.features':'オプション機能を設定','wizard.memory':'メモリを初期化','wizard.completion':'シェル補完','wizard.save':'設定を保存','wizard.complete':'✅ セットアップ完了！','common.enabled':'有効','common.disabled':'無効'}
};
let currentLocale = DEFAULT_LOCALE;
export async function initializeI18n(localeOverride = null) {
  if (localeOverride) return setLocale(localeOverride);
  try { if (await fs.pathExists(CONFIG_PATH)) { const config = await fs.readJson(CONFIG_PATH); const saved = config.locale || config.locales?.[0]; if (SUPPORTED_LOCALES.includes(saved)) { currentLocale = saved; return currentLocale; } } } catch {}
  const envLocale = (process.env.LC_ALL || process.env.LC_MESSAGES || process.env.LANG || '').split(/[._-]/)[0];
  if (SUPPORTED_LOCALES.includes(envLocale)) currentLocale = envLocale;
  return currentLocale;
}
export function setLocale(locale) { if (!SUPPORTED_LOCALES.includes(locale)) throw new Error(t('error.invalidLocale', { locale })); currentLocale = locale; return currentLocale; }
export function getLocale() { return currentLocale; }
export function getSupportedLocales() { return [...SUPPORTED_LOCALES]; }
export function t(key, values = {}) { const template = translations[currentLocale]?.[key] || translations.en[key] || key; return template.replace(/\{(\w+)\}/g, (_, name) => values[name] ?? `{${name}}`); }
export function isYes(value) { return ['y','yes','o','oui','s','si','sí','j','ja','是','はい'].includes(value.trim().toLowerCase()); }
export function isNo(value) { return ['n','no','non','nein','否','いいえ'].includes(value.trim().toLowerCase()); }
