# Fish completion for claude-antislop
complete -c claude-antislop -f
complete -c claude-antislop -n '__fish_use_subcommand' -a install -d 'Install the plugin'
complete -c claude-antislop -n '__fish_use_subcommand' -a status -d 'Show status'
complete -c claude-antislop -n '__fish_use_subcommand' -a scan -d 'Scan a repository'
complete -c claude-antislop -n '__fish_use_subcommand' -a learn-from-git -d 'Learn from Git'
complete -c claude-antislop -n '__fish_use_subcommand' -a memory-search -d 'Search memory'
complete -c claude-antislop -n '__fish_use_subcommand' -a memory-write -d 'Write to memory'
complete -c claude-antislop -n '__fish_use_subcommand' -a code-quality-check -d 'Run quality checks'
complete -c claude-antislop -n '__fish_use_subcommand' -a mcp-server -d 'Start MCP server'
complete -c claude-antislop -n '__fish_use_subcommand' -a init-memory -d 'Initialize memory'
complete -c claude-antislop -n '__fish_use_subcommand' -a completion -d 'Print/install completions'
complete -c claude-antislop -s h -l help -d 'Show help'
complete -c claude-antislop -s V -l version -d 'Show version'
complete -c claude-antislop -n '__fish_seen_subcommand_from install' -l init-memory -d 'Initialize memory'
complete -c claude-antislop -n '__fish_seen_subcommand_from install' -l verbose -d 'Detailed output'
complete -c claude-antislop -n '__fish_seen_subcommand_from status' -l verbose -d 'Detailed diagnostics'
complete -c claude-antislop -n '__fish_seen_subcommand_from scan' -l repo -r -a '(__fish_complete_directories)' -d 'Repository path'
complete -c claude-antislop -n '__fish_seen_subcommand_from scan' -l output -r -a '(__fish_complete_directories)' -d 'Output directory'
complete -c claude-antislop -n '__fish_seen_subcommand_from scan' -l verbose -d 'Detailed output'
complete -c claude-antislop -n '__fish_seen_subcommand_from learn-from-git' -l repo -r -a '(__fish_complete_directories)' -d 'Repository path'
complete -c claude-antislop -n '__fish_seen_subcommand_from learn-from-git' -l recent -r -a '1d 7d 14d 30d 60d 90d 3m 6m 1y' -d 'Time period'
complete -c claude-antislop -n '__fish_seen_subcommand_from learn-from-git' -l verbose -d 'Detailed output'
complete -c claude-antislop -n '__fish_seen_subcommand_from memory-search' -l query -r -d 'Search query'
complete -c claude-antislop -n '__fish_seen_subcommand_from memory-search' -l category -r -a 'all standards patterns anti-patterns insights reviews' -d 'Category'
complete -c claude-antislop -n '__fish_seen_subcommand_from memory-search' -l limit -r -d 'Maximum results'
complete -c claude-antislop -n '__fish_seen_subcommand_from memory-search' -l fuzzy -d 'Use fuzzy matching'
complete -c claude-antislop -n '__fish_seen_subcommand_from memory-write' -l category -r -a 'standards patterns anti-patterns insights reviews' -d 'Category'
complete -c claude-antislop -n '__fish_seen_subcommand_from memory-write' -l filename -r -a '(__fish_complete_path)' -d 'Filename'
complete -c claude-antislop -n '__fish_seen_subcommand_from memory-write' -l content -r -d 'Content'
complete -c claude-antislop -n '__fish_seen_subcommand_from memory-write' -l append -d 'Append content'
complete -c claude-antislop -n '__fish_seen_subcommand_from code-quality-check' -l code -r -d 'Code to check'
complete -c claude-antislop -n '__fish_seen_subcommand_from code-quality-check' -l language -r -a 'javascript typescript' -d 'Language'
complete -c claude-antislop -n '__fish_seen_subcommand_from code-quality-check' -l checks -r -a 'lint typecheck prettier' -d 'Checks'
complete -c claude-antislop -n '__fish_seen_subcommand_from init-memory' -l force -d 'Overwrite'
complete -c claude-antislop -n '__fish_seen_subcommand_from init-memory' -l verbose -d 'Detailed output'
complete -c claude-antislop -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish install' -d 'Shell or install'
complete -c claude-antislop -n '__fish_seen_subcommand_from completion' -l path -r -a '(__fish_complete_directories)' -d 'Completion directory'
